<?php

declare(strict_types=1);

// GENERATED by cargo xtask gen-host-facts. Do not edit by hand.

namespace Phalanx\Bia\Runtime\Host;

use InvalidArgumentException;

final class EnvFacts
{
    /** @param list<string> $sources @param array<string, array{value: string, source: string, line: ?int}> $values @param list<array{severity: string, code: string, message: string, key: ?string, source: ?string, line: ?int}> $issues */
    public function __construct(
        private(set) array $sources,
        private(set) array $values,
        private(set) array $issues,
    ) {
    }

    /** @param array<string, mixed> $data */
    public static function hydrate(array $data): self
    {
        self::assertShape($data, ['sources', 'values', 'issues'], 'EnvFacts');
        $sources = self::listOfString($data['sources'], 'EnvFacts.sources');
        if (!is_array($data['values'])) { throw new InvalidArgumentException('EnvFacts.values must be object.'); }
        $values = [];
        foreach ($data['values'] as $key => $value) {
            if (!is_string($key) || !is_array($value)) { throw new InvalidArgumentException('EnvFacts.values must be array<string, object>.'); }
            self::assertShape($value, ['value', 'source', 'line'], 'EnvFacts.values.' . $key);
            if (!is_string($value['value']) || !is_string($value['source']) || ($value['line'] !== null && !is_int($value['line']))) { throw new InvalidArgumentException('EnvFacts.values.' . $key . ' has invalid fields.'); }
            $values[$key] = ['value' => $value['value'], 'source' => $value['source'], 'line' => $value['line']];
        }
        if (!is_array($data['issues']) || array_is_list($data['issues']) === false) { throw new InvalidArgumentException('EnvFacts.issues must be list<object>.'); }
        $issues = [];
        foreach ($data['issues'] as $issue) {
            if (!is_array($issue)) { throw new InvalidArgumentException('EnvFacts.issues must be list<object>.'); }
            self::assertShape($issue, ['severity', 'code', 'message', 'key', 'source', 'line'], 'EnvFacts.issue');
            if (!is_string($issue['severity']) || !in_array($issue['severity'], ['warn', 'error'], true)) { throw new InvalidArgumentException('EnvFacts.issue.severity must be warn|error.'); }
            if (!is_string($issue['code']) || !is_string($issue['message'])) { throw new InvalidArgumentException('EnvFacts.issue code/message must be strings.'); }
            if ($issue['key'] !== null && !is_string($issue['key'])) { throw new InvalidArgumentException('EnvFacts.issue.key must be string|null.'); }
            if ($issue['source'] !== null && !is_string($issue['source'])) { throw new InvalidArgumentException('EnvFacts.issue.source must be string|null.'); }
            if ($issue['line'] !== null && !is_int($issue['line'])) { throw new InvalidArgumentException('EnvFacts.issue.line must be int|null.'); }
            $issues[] = $issue;
        }
        return new self($sources, $values, $issues);
    }

    /** @return array{sources: list<string>, values: object, issues: list<array{severity: string, code: string, message: string, key: ?string, source: ?string, line: ?int}>} */
    public function toArray(): array
    {
        return ['sources' => $this->sources, 'values' => $this->values === [] ? (object) [] : $this->values, 'issues' => $this->issues];
    }

    /** @return list<string> */
    private static function listOfString(mixed $value, string $path): array
    {
        if (!is_array($value) || array_is_list($value) === false) {
            throw new InvalidArgumentException("{$path} must be list<string>.");
        }

        foreach ($value as $item) {
            if (!is_string($item)) {
                throw new InvalidArgumentException("{$path} must be list<string>.");
            }
        }

        return $value;
    }

    /** @param array<string, mixed> $data @param list<string> $keys */
    private static function assertShape(array $data, array $keys, string $type): void
    {
        $actual = array_keys($data);
        $missing = array_values(array_diff($keys, $actual));
        $unknown = array_values(array_diff($actual, $keys));

        if ($missing !== []) {
            throw new InvalidArgumentException($type . ' missing keys: ' . implode(', ', $missing));
        }

        if ($unknown !== []) {
            throw new InvalidArgumentException($type . ' unknown keys: ' . implode(', ', $unknown));
        }
    }

}
